# Generated by Django 2.2 on 2020-11-01 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailingApp', '0002_auto_20201101_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmail',
            options={'verbose_name': '테스트 메일'},
        ),
        migrations.RemoveField(
            model_name='testmail',
            name='when_to_send',
        ),
        migrations.AddField(
            model_name='testmail',
            name='has_been_sent',
            field=models.BooleanField(default=False, verbose_name='전송 여부'),
        ),
        migrations.AddField(
            model_name='testmail',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 19, 23, 30, 105725), verbose_name='발송 시각'),
        ),
        migrations.AlterField(
            model_name='testmail',
            name='content',
            field=models.TextField(verbose_name='본문'),
        ),
        migrations.AlterField(
            model_name='testmail',
            name='receiver',
            field=models.EmailField(max_length=254, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='testmail',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='제목'),
        ),
    ]
