# Generated by Django 2.2 on 2020-10-27 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=15, unique=True, verbose_name='닉네임')),
                ('image', models.ImageField(blank=True, default='accountApp/profile_image/user_default_image.png', null=True, upload_to='accountApp/profile_image', verbose_name='대표 이미지')),
                ('introduce', models.TextField(blank=True, default='', verbose_name='소개글')),
                ('email_authenticated', models.BooleanField(default=False, verbose_name='이메일 인증 여부')),
                ('email_auth_code', models.CharField(default='', max_length=8, verbose_name='이메일 인증 코드')),
                ('last_auth_code_request', models.DateTimeField(auto_now_add=True, verbose_name='마지막 인증 코드 요청')),
                ('last_email_modified', models.DateTimeField(auto_now_add=True, verbose_name='마지막 이메일 재설정')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='유저 레벨')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='대상 유저')),
            ],
            options={
                'verbose_name': '유저 정보',
            },
        ),
    ]
