# Generated by Django 3.1.1 on 2020-09-29 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_auth_code_request',
            field=models.DateTimeField(auto_now_add=True,
                                       default=datetime.datetime(2020,
                                                                 9,
                                                                 29,
                                                                 15,
                                                                 44,
                                                                 24,
                                                                 488068,
                                                                 tzinfo=utc),
                                       verbose_name='마지막 인증 코드 요청'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_email_modified',
            field=models.DateTimeField(auto_now_add=True,
                                       default=django.utils.timezone.now,
                                       verbose_name='마지막 이메일 재설정'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='유저 레벨'),
        ),
    ]
